name: Sync GitHub issues to Jira
on: [issues, issue_comment]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ubuntu-22.04
    steps:
      - uses: ubuntu/sync-issues-github-jira@v1
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
          component: "WSL"
