name: Test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci-ci.yaml
      - name: Test
        shell: bash
        run: |
          go test -race

  test-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test
        shell: powershell
        run: |
          go.exe test # -race not supported on Windows