name: Test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci-ci.yaml

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        shell: bash
        run: |
          go test -race

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        shell: powershell
        run: |
          go test
          # -race not supported on Windows